spring:
  datasource:
    url: jdbc:h2:mem:sharecycle;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: false

server:
  port: 8080
