name: Backend CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Backend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java (Temurin 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Build and test with Maven Wrapper
        run: ./mvnw -B verify
        working-directory: src/backend
